### ISSUE TITLE
Sargasso documentation

### ISSUE THREAD

**Issue by blanleung** [statbio/Sargasso#107]
Hi,
Where can we find the latest documentation for Sargasso? The provided link is dead.
Thanks !

**Comment by lweasel** [comment]
Hi @benhur974 - many thanks for bringing this to my attention! The name of the parent GitHub organisation has changed, and I hadn't realised that this had broken the link to the documentation. The correct URL is now:

http://biomedicalinformaticsgroup.github.io/Sargasso/

**Comment by blanleung** [comment]
Thanks !
