### ISSUE TITLE
Cope with unequal paired-end read lengths

### ISSUE THREAD

**Issue by lweasel** [statbio/Sargasso#55]
hits_checker.py assumes that both reads of every pair are the same length. However this is not necessarily the case - eg. data where all first reads are 76bp and all second reads are 75b. Depending on which strand the pair maps, this may mean that the pair is considered to be of different lengths for different species, and the code for determining whether minmatch or mismatch thresholds has been violated can go haywire.

**Comment by hxin** [comment]
will be fix with #64
