### ISSUE TITLE
Inconsistent use of mismatches in thresholds

### ISSUE THREAD

**Issue by lweasel** [statbio/Sargasso#56]
In hits_checker.py , the method check_hits() compares the maximum number of mismatches for a set of mappings for a read against the mismatch threshold. But _check_thresholds compares the minimum number of mismatches against the threshold. I think that these should both use the minimum number of mismatches?

**Comment by hxin** [comment]
in the branch but need to be tested to see the effect. 
#59 

The continuous-integration check fails but this is expected since the desition making structure has been changed.
