### ISSUE TITLE
Adding a <dev> branch as pre-release 

### ISSUE THREAD

**Issue by hxin** [statbio/Sargasso#70]
I was fixing #69 when I realized that we might need a dev/pre-release branch to avoid committing everything to master once they are ready.  The <dev> branch should be used where we commit the changes until they are enough for a new release. Only the dev branch can be merged into master so that the dev will always be ahead of master. This also keeps the 'release' clean. What do you think?@lweasel

**Comment by hxin** [comment]
This also keeps the master/release consistency, so when user install Sargasso with:
pip install git+https://github.com/statbio/Sargasso.git
They are installing the version in the release note, rather than some version ahead of the release.

**Comment by lweasel** [comment]
Yes, makes complete sense going forward from now - let's do this.

**Comment by hxin** [comment]
dev was created.
