### ISSUE TITLE
Check code speed vs latest release.

### ISSUE THREAD

**Issue by lweasel** [statbio/Sargasso#87]

**Comment by hxin** [comment]
I tested the speed of the current master verson 76f536f7d23d4b369d167bde0111a62d0aabe63a against the dev version f79200f996f65be41bff0b94f535bc0a3cb36426, to make sure the refactoring of the dna-seq is not slowing down the code. 

The test data is:
'rna_mouse_11|rnaseq|mouse|/srv/data/ghardingham/activity_dependence_nora|_1.sanfastq.gz|_2.sanfastq.gz|AM1,AM2'

The result shows that filter_sample_reads took almost the same time between the versions, suggesting that the refactoring is at least not slowing down the code, which is as expected.

  | Data.Name | Sargasso.Strategy | difference(days) | original
-- | -- | -- | -- | --
1 | rna_mouse_11 | best | -0.0006481 | dev=00:43:09,master=00:42:13
2 | rna_mouse_11 | conservative | -0.0001505 | dev=00:38:22,master=00:38:09
3 | rna_mouse_11 | permissive | -0.0003935 | dev=00:44:59,master=00:44:25
4 | rna_mouse_11 | recall | -0.0005671 | dev=00:44:44,master=00:43:55
