### ISSUE TITLE
Confirm that v2 code works with both Python 2 and Python 3.

### ISSUE THREAD

**Issue by lweasel** [statbio/Sargasso#92]

**Comment by lweasel** [comment]
Final run over sets of test data in both Python 2 and Python 3?

**Comment by hxin** [comment]
Started two python ve with py2 and py3.
Will run a rna dataset and one dna dataset in each ve with d7e4caab7a5eb04e2abc7be657b4ed0772f23756.

Will comfirm later.

**Comment by hxin** [comment]
```bash

mkproject Sargasso_testing_1
pip install git+https://github.com/statbio/Sargasso.git@7123745b9250ed6efa692d633d796c3c4a3d2ca2

species_separator rnaseq --run-separation --reads-base-dir="/" -t 8 --best /srv/data/sargasso/pre_built/rna_mouse_11/samples.tsv /home/xinhe/tmp/sargasso_dev_run/rna_mouse_11 mouse /srv/data/genome/mouse/ensembl-94/STAR_indices/primary_assembly rat /srv/data/genome/rat/ensembl-94/STAR_indices/toplevel human /srv/data/genome/human/ensembl-94/STAR_indices/primary_assembly

species_separator dnaseq --run-separation --reads-base-dir="/" -t 8 --best /srv/data/sargasso/pre_built/dna_human/samples.tsv /home/xinhe/tmp/sargasso_dev_run/dna_human mouse /srv/data/genome/mouse/ensembl-94/bowtie2_indices/primary_assembly/ rat /srv/data/genome/rat/ensembl-94/bowtie2_indices/toplevel/ human /srv/data/genome/human/ensembl-94/bowtie2_indices/primary_assembly/


mkproject --python=/usr/bin/python3 Sargasso_testing_2
pip install git+https://github.com/statbio/Sargasso.git@7123745b9250ed6efa692d633d796c3c4a3d2ca2

species_separator rnaseq --run-separation --reads-base-dir="/" -t 8 --best /srv/data/sargasso/pre_built/rna_mouse_11/samples.tsv /home/xinhe/tmp/sargasso_dev_run/rna_mouse_11_py3 mouse /srv/data/genome/mouse/ensembl-94/STAR_indices/primary_assembly rat /srv/data/genome/rat/ensembl-94/STAR_indices/toplevel human /srv/data/genome/human/ensembl-94/STAR_indices/primary_assembly

species_separator dnaseq --run-separation --reads-base-dir="/" -t 8 --best /srv/data/sargasso/pre_built/dna_human/samples.tsv /home/xinhe/tmp/sargasso_dev_run/dna_human_py3 mouse /srv/data/genome/mouse/ensembl-94/bowtie2_indices/primary_assembly/ rat /srv/data/genome/rat/ensembl-94/bowtie2_indices/toplevel/ human /srv/data/genome/human/ensembl-94/bowtie2_indices/primary_assembly/

```

**Comment by hxin** [comment]
Python2/3 went through and produced the same results.

./dna_human_py3/filtered_reads/overall_filtering_summary.txt
Sample,Assigned-Hits-mouse,Assigned-Reads-mouse,Rejected-Hits-mouse,Rejected-Reads-mouse,Ambiguous-Hits-mouse,Ambiguous-Reads-mouse,Assigned-Hits-rat,Assigned-Reads-rat,Rejected-Hits-rat,Rejected-Reads-rat,Ambiguous-Hits-rat,Ambiguous-Reads-rat,Assigned-Hits-human,Assigned-Reads-human,Rejected-Hits-human,Rejected-Reads-human,Ambiguous-Hits-human,Ambiguous-Reads-human
SRR7968966,20082,2037,666114,56578,39322,3837,37392,10125,523830,147879,40152,3836,134521686,23519616,6981766,514624,42760,4002
SRR7968960,40222,4775,864094,77170,111486,6404,89226,15386,968632,196807,117600,6512,178656564,31276919,9312954,664062,121462,6708

./dna_human/filtered_reads/overall_filtering_summary.txt
Sample,Assigned-Hits-mouse,Assigned-Reads-mouse,Rejected-Hits-mouse,Rejected-Reads-mouse,Ambiguous-Hits-mouse,Ambiguous-Reads-mouse,Assigned-Hits-rat,Assigned-Reads-rat,Rejected-Hits-rat,Rejected-Reads-rat,Ambiguous-Hits-rat,Ambiguous-Reads-rat,Assigned-Hits-human,Assigned-Reads-human,Rejected-Hits-human,Rejected-Reads-human,Ambiguous-Hits-human,Ambiguous-Reads-human
SRR7968966,20082,2037,666114,56578,39322,3837,37392,10125,523830,147879,40152,3836,134521644,23519614,6981808,514626,42760,4002
SRR7968960,40222,4775,864094,77170,111486,6404,89226,15386,968632,196807,117600,6512,178656568,31276921,9312950,664060,121462,6708

./rna_mouse_11_py3/filtered_reads/overall_filtering_summary.txt
Sample,Assigned-Hits-mouse,Assigned-Reads-mouse,Rejected-Hits-mouse,Rejected-Reads-mouse,Ambiguous-Hits-mouse,Ambiguous-Reads-mouse,Assigned-Hits-rat,Assigned-Reads-rat,Rejected-Hits-rat,Rejected-Reads-rat,Ambiguous-Hits-rat,Ambiguous-Reads-rat,Assigned-Hits-human,Assigned-Reads-human,Rejected-Hits-human,Rejected-Reads-human,Ambiguous-Hits-human,Ambiguous-Reads-human
AM1,54206866,23753708,3043604,1219320,1067912,498232,1121374,138917,27349278,11164283,1168888,503235,657520,50777,9292578,3219505,781908,300368
AM2,79954828,34670617,4599170,1833066,1584982,730333,2166702,254523,41234556,16382327,1770996,739835,1315510,97619,15044482,4788576,1221812,446132

./rna_mouse_11/filtered_reads/overall_filtering_summary.txt
Sample,Assigned-Hits-mouse,Assigned-Reads-mouse,Rejected-Hits-mouse,Rejected-Reads-mouse,Ambiguous-Hits-mouse,Ambiguous-Reads-mouse,Assigned-Hits-rat,Assigned-Reads-rat,Rejected-Hits-rat,Rejected-Reads-rat,Ambiguous-Hits-rat,Ambiguous-Reads-rat,Assigned-Hits-human,Assigned-Reads-human,Rejected-Hits-human,Rejected-Reads-human,Ambiguous-Hits-human,Ambiguous-Reads-human
AM1,54206866,23753708,3043604,1219320,1067912,498232,1121374,138917,27349278,11164283,1168888,503235,657520,50777,9292578,3219505,781908,300368
AM2,79954828,34670617,4599170,1833066,1584982,730333,2166702,254523,41234556,16382327,1770996,739835,1315510,97619,15044482,4788576,1221812,446132
